<a href="https://colab.research.google.com/github/nomiasif20/-datasciencecoursera/blob/master/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [5]:
scaler = tf.constant(7)

In [6]:
scaler.ndim

0

In [8]:
vector = tf.constant([5,5])

In [9]:
vector.ndim

1

In [12]:
matrix=tf.constant([[1,2],[3,4],[5,6]])

In [13]:
matrix.ndim

2

In [14]:
tensor =tf.constant([[[1,2,3],
                      [4,5,6]]])

In [16]:
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [18]:
tensor.ndim

3

In [18]:
####Addition###

In [22]:
tensornew = tensor + 10
tensornew

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16]]], dtype=int32)>

In [23]:
####SUBTRACTION###
tensornew - 7

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [18]:
x 